name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:
    repository_dispatch:
        types: [on-millennium-sdk-updated]

permissions:
    checks: write
    contents: read
    pull-requests: write

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '20'

            - name: Authenticate SteamBrew
              run: echo "$FIREBASE_CREDENTIALS" | base64 -d > ./apps/www/credentials.json && echo "$BEARER" > ./apps/www/.env
              env:
                  FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
                  BEARER: ${{ secrets.BEARER }}

            - name: Install pnpm
              run: npm install -g pnpm && pnpm install && pnpm run build

            - name: Install Firebase Tools
              run: |
                  npm install -g firebase-tools
                  firebase experiments:enable webframeworks

            - name: Deploy Documentation
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                  cd apps/docs
                  firebase use --add steam-brew
                  firebase target:apply hosting steambrew-docs steambrew-docs       
                  firebase deploy --only hosting --token $FIREBASE_TOKEN --force

            - name: Deploy Main Site
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
              run: |
                  cd apps/www
                  firebase use --add steam-brew
                  firebase target:apply hosting steam-brew steam-brew
                  firebase deploy --only hosting --token $FIREBASE_TOKEN --force
